### ISSUE TITLE
Make permanent on Linux

### ISSUE THREAD

**Issue by krillin666** [pieter-degroote/UltimateKEYS#15]
Hey @pieter-degroote , 
Thanks for this amazing layout. I've changed it quite extensible to accommodate my needs, but now I would like to make it permanent on my setup. 
I use Fedora with Gnome on Xorg, do you know of a way to register this in a permanent way ?

Thank you for your time !

**Comment by pieter-degroote** [comment]
Well, on the website you can find some information about integrating it into the main setup/startup :

https://pieter-degroote.github.io/UltimateKEYS/
https://pieter-degroote.github.io/UltimateKEYS/linux-xkb.html
https://pieter-degroote.github.io/UltimateKEYS/linux-xmodmap.html

Personally, I recommend using a non-intrusive method (without 'root') for the integration. In case you really want to go ahead with 'root' access, be sure to do this on a virtual machine with a preliminary (initial) snapshot.
That way, you can always revert and undo those 'intrusive' changes...

Please note that I am considering to make a newer version of the layout which should rather look like this concept (prototype) :

![UltimateKEYS (prototype) - Keyboard Layout Image](https://raw.githubusercontent.com/pieter-degroote/lab-tests-concepts/master/ultimatekeys-v2-concepts/UltimateKEYS%20v2%20-%20Keyboard%20Layout%20Image.png)

This prototype features a single 'Compose' key (Multi_key), enabling access to lots of special letters/characters.

Enjoy, have fun, and stay safe !

**Comment by pieter-degroote** [comment]
I hope that the links specified in my previous post could result in an acceptable outcome for you.
Hopefully, you can now use the layout (or a customized version) the way it should be.

(Please note that the latest version features a somewhat different approach, since it comes with a 'Compose key' (or Multi_key) instead.)

**Comment by pieter-degroote** [comment]
As for now, it turns out that the easiest and simplest approach is to:

- Create your customized layout with the name: custom
- Put that "custom" file into "/usr/share/X11/xkb/symbols/" (root required).
- Activate the layout on your desktop via the keyboard settings by selecting "A user-defined custom Layout".

See also: [UltimateKEYS - XKB integration](https://pieter-degroote.github.io/UltimateKEYS/linux-xkb.html) (updated)

Note that supplying your own keyboard layout as "custom" is supported from xkeyboard-config 2.33 onwards, since it already pre-defined there (https://who-t.blogspot.com/2021/02/a-pre-supplied-custom-keyboard-layout.html).
