### ISSUE TITLE
AltGr dead keys via MSKLC not showing on On-Screen Keyboard

### ISSUE THREAD

**Issue by dazu89** [pieter-degroote/UltimateKEYS#18]
Useful layout, thank you for sharing the source files! It noticed however, that the AltGr dead keys do not show on the On-Screen Keyboard (OSK) under Windows 10, Version 10.0.19045. In my experience, the OSK, apart from prints, can ease transition to another layout considerably. Do you have any idea, why this bug occurs and how it could be remedied? Or maybe you know of another alternative to OSK. 
Best regards, 
Daniel

**Comment by pieter-degroote** [comment]
Well, I just tested the MSKLC version on a Windows 10 session (version 10.0.19045, on VirtualBox).

Unfortunately, the On-Screen Keyboard (OSK) **_does not_** show the AltGr and AltGr+Shift layers on my installation either.
I have tested this now with different layouts, like UltimateKEYS and also some layouts integrated in Windows (for instance, US-International, UK Extended, Belgian (Period)). They all seem to have the exact same shortcomings when it comes down to the AltGr and AltGr+Shift layers.

Further testing showed that the AltGr and AltGr+Shift layers sometimes showed up when using the layouts from Windows itself, although I believe that the OSK has not been that thoroughly tested by Microsoft...
When I switched (or cycled) between those different layouts, the OSK once displayed the wrong layouts (perhaps a bug in OSK), although it worked fine again during a second test.

I also noted that the AltGr and AltGr+Shift layers show up on US-International, but not on Belgian (Period), UK Extended and UltimateKEYS.
Even though, when not showing up, the AltGr and AltGr+Shift layers can still be used: clicking Right Alt, followed by 'l/L' (or clicking Right Alt, Shift, L) resulted in 'ø' (or 'Ø') anyway, being entered into Notepad.

Please note that the MSKLC version of UltimateKEYS is a slimmed-down version, since MSKLC does not support multiple keystrokes as a sequence for a dead key. That way, a 'Compose Key' is not possible.
That way, the MSKLC version is the exception on rule as it has no dead keys (and no AltGr dead keys either).

See also: https://pieter-degroote.github.io/UltimateKEYS/integration-msklc.html

Hopefully, this can help.
